# Generated by Django 3.2.6 on 2021-10-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_addressbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
