# Generated by Django 3.2.6 on 2021-10-15 14:53

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
