# Generated by Django 3.2.6 on 2021-10-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
