# Generated by Django 3.2.6 on 2021-10-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0007_remove_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Interest',
            new_name='name',
        ),
    ]
