# Generated by Django 3.2.6 on 2021-10-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0008_auto_20211015_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(choices=[('novels', 'novels'), ('stories', 'stories'), ('short_stories', 'short_stories'), ('comics', 'comics'), ('science', 'science'), ('science', 'science'), ('education', 'education'), ('language_lit', 'language_lit'), ('biography', 'biography')], default='novels', max_length=15),
        ),
    ]
