# Generated by Django 3.2.6 on 2021-10-16 08:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0009_alter_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
