# Generated by Django 3.2.6 on 2021-11-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0012_user_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop_name',
        ),
    ]
