# Generated by Django 3.2.6 on 2021-11-25 15:30

import BookApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catogory', models.CharField(choices=[('novels', 'novels'), ('stories', 'stories'), ('short_stories', 'short_stories'), ('comics', 'comics'), ('science', 'science'), ('science', 'science'), ('education', 'education'), ('language_lit', 'language_lit'), ('biography', 'biography')], default='novels', max_length=15)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('ISBN10', models.BigIntegerField(null=True)),
                ('ISBN13', models.BigIntegerField(null=True)),
                ('PublicationDate', models.IntegerField(choices=[(1700, 1700), (1701, 1701), (1702, 1702), (1703, 1703), (1704, 1704), (1705, 1705), (1706, 1706), (1707, 1707), (1708, 1708), (1709, 1709), (1710, 1710), (1711, 1711), (1712, 1712), (1713, 1713), (1714, 1714), (1715, 1715), (1716, 1716), (1717, 1717), (1718, 1718), (1719, 1719), (1720, 1720), (1721, 1721), (1722, 1722), (1723, 1723), (1724, 1724), (1725, 1725), (1726, 1726), (1727, 1727), (1728, 1728), (1729, 1729), (1730, 1730), (1731, 1731), (1732, 1732), (1733, 1733), (1734, 1734), (1735, 1735), (1736, 1736), (1737, 1737), (1738, 1738), (1739, 1739), (1740, 1740), (1741, 1741), (1742, 1742), (1743, 1743), (1744, 1744), (1745, 1745), (1746, 1746), (1747, 1747), (1748, 1748), (1749, 1749), (1750, 1750), (1751, 1751), (1752, 1752), (1753, 1753), (1754, 1754), (1755, 1755), (1756, 1756), (1757, 1757), (1758, 1758), (1759, 1759), (1760, 1760), (1761, 1761), (1762, 1762), (1763, 1763), (1764, 1764), (1765, 1765), (1766, 1766), (1767, 1767), (1768, 1768), (1769, 1769), (1770, 1770), (1771, 1771), (1772, 1772), (1773, 1773), (1774, 1774), (1775, 1775), (1776, 1776), (1777, 1777), (1778, 1778), (1779, 1779), (1780, 1780), (1781, 1781), (1782, 1782), (1783, 1783), (1784, 1784), (1785, 1785), (1786, 1786), (1787, 1787), (1788, 1788), (1789, 1789), (1790, 1790), (1791, 1791), (1792, 1792), (1793, 1793), (1794, 1794), (1795, 1795), (1796, 1796), (1797, 1797), (1798, 1798), (1799, 1799), (1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=BookApp.models.current_year, null=True)),
                ('Rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('CopyRightInfo', models.TextField(blank=True, null=True)),
                ('NumberOfCopy', models.IntegerField(blank=True)),
                ('Caption', models.CharField(max_length=50)),
                ('Description', models.TextField(null=True)),
                ('Condition', models.CharField(blank=True, choices=[('good', 'good'), ('damaged', 'damaged')], max_length=8)),
                ('Quality', models.CharField(blank=True, choices=[('new', 'new'), ('old', 'old')], max_length=3)),
                ('Size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('B3', 'B3'), ('b5', 'b5')], default='A5', max_length=8)),
                ('FrontCover', models.ImageField(upload_to=None)),
                ('BackCover', models.ImageField(blank=True, upload_to=None)),
                ('FirstPage', models.ImageField(blank=True, upload_to=None)),
                ('Body2nd', models.ImageField(blank=True, upload_to=None)),
                ('PageInside', models.ImageField(blank=True, upload_to=None)),
                ('DamagedPart', models.ImageField(blank=True, upload_to=None)),
                ('is_free', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('Author', models.ManyToManyField(to='BookApp.Author')),
                ('Publisher', models.ManyToManyField(blank=True, to='BookApp.Publisher')),
                ('Seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
