# Generated by Django 3.2.6 on 2021-11-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BackCover',
            field=models.ImageField(blank=True, help_text='Back cover page Image of the book', upload_to=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='Body2nd',
            field=models.ImageField(blank=True, help_text='Body 2nd page Image of the book', upload_to=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='DamagedPart',
            field=models.ImageField(blank=True, help_text='Damaged page Image of the book', upload_to=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='FirstPage',
            field=models.ImageField(blank=True, help_text='First page Image of the book', upload_to=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='FrontCover',
            field=models.ImageField(help_text='Front cover page Image of the book', upload_to=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='PageInside',
            field=models.ImageField(blank=True, help_text='page inside Image of the book', upload_to=None),
        ),
    ]
