# Generated by Django 3.2.6 on 2021-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_auto_20211127_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Length',
            field=models.IntegerField(blank=True, help_text='Weight of the book per Grams', null=True),
        ),
    ]
