# Generated by Django 3.2.6 on 2021-11-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_book_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Price',
            field=models.DecimalField(decimal_places=2, help_text='Price in LKR', max_digits=10, null=True),
        ),
    ]
