# Generated by Django 3.2.6 on 2021-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='NumberOfCopy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
