# Generated by Django 3.2.6 on 2021-12-03 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_auto_20211202_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
