# Generated by Django 3.2.6 on 2021-12-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthApp', '0013_remove_user_shop_name'),
        ('BookApp', '0006_alter_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('Total_Price', models.IntegerField()),
                ('Is_shipped', models.BooleanField(default=0)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.addressbook')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookApp.book')),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
