# Generated by Django 3.2.6 on 2021-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0007_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN10',
            new_name='ISBN',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='is_available',
            new_name='is_stock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ISBN13',
        ),
        migrations.AddField(
            model_name='book',
            name='Language',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
