# Generated by Django 3.2.6 on 2021-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0009_auto_20211210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Upload_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
